"""empty message

Revision ID: a7e52a5f70c8
Revises: 
Create Date: 2021-05-18 11:57:03.968989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e52a5f70c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ticker', sa.String(length=5), nullable=True),
    sa.Column('shares_outstanding', sa.Integer(), nullable=False),
    sa.Column('share_price', sa.Float(), nullable=False),
    sa.Column('ipo_price', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=False),
    sa.Column('price_earnings', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_index(op.f('ix_company_ticker'), 'company', ['ticker'], unique=True)
    op.create_table('market_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('share_price', sa.Float(), nullable=False),
    sa.Column('time_placed', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('time_executed', sa.DateTime(), nullable=False),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    op.drop_table('market_order')
    op.drop_index(op.f('ix_company_ticker'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
